// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaPBbzGNoArmutCNQSwOzXWXJQeZscWm0',
    appId: '1:836688939884:web:aa753774d1b2067c2c0149',
    messagingSenderId: '836688939884',
    projectId: 'pozo-tesis-app',
    authDomain: 'pozo-tesis-app.firebaseapp.com',
    storageBucket: 'pozo-tesis-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5ynWclV76gc8q2RsyX_7aOU-F6Slp_VU',
    appId: '1:836688939884:android:126a561d7b1191922c0149',
    messagingSenderId: '836688939884',
    projectId: 'pozo-tesis-app',
    storageBucket: 'pozo-tesis-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHXsyeuACFJOlnw-pmCVV55crnO0p8Z8w',
    appId: '1:836688939884:ios:07f38ed2b11217b42c0149',
    messagingSenderId: '836688939884',
    projectId: 'pozo-tesis-app',
    storageBucket: 'pozo-tesis-app.firebasestorage.app',
    iosBundleId: 'com.example.hola',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHXsyeuACFJOlnw-pmCVV55crnO0p8Z8w',
    appId: '1:836688939884:ios:07f38ed2b11217b42c0149',
    messagingSenderId: '836688939884',
    projectId: 'pozo-tesis-app',
    storageBucket: 'pozo-tesis-app.firebasestorage.app',
    iosBundleId: 'com.example.hola',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaPBbzGNoArmutCNQSwOzXWXJQeZscWm0',
    appId: '1:836688939884:web:fec77d0ae8d022622c0149',
    messagingSenderId: '836688939884',
    projectId: 'pozo-tesis-app',
    authDomain: 'pozo-tesis-app.firebaseapp.com',
    storageBucket: 'pozo-tesis-app.firebasestorage.app',
  );
}
